language: node_js

os:
  - osx

node_js:
  - "lts/*"

cache: yarn

cache:
  directories:
  - node_modules

before_script:
  - "npm install -g yarn"
  - "yarn global add gatsby-cli"

script:
  - "gatsby build"

